// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBj05IIio8fdDxMJcQAo3VTSb-PQMeG4Do',
    appId: '1:707566372207:web:b570aeea68183d229d549a',
    messagingSenderId: '707566372207',
    projectId: 'texnik-ijodkorlik-ilhom-45503',
    authDomain: 'texnik-ijodkorlik-ilhom-45503.firebaseapp.com',
    storageBucket: 'texnik-ijodkorlik-ilhom-45503.firebasestorage.app',
    measurementId: 'G-MWF1W2P8VV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAtxafZ5s6QjHUo3GTeylZhCD5epKSwuNI',
    appId: '1:707566372207:android:00f97156d1df4e2b9d549a',
    messagingSenderId: '707566372207',
    projectId: 'texnik-ijodkorlik-ilhom-45503',
    storageBucket: 'texnik-ijodkorlik-ilhom-45503.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBIGuWSDiF_DF0I2w-OBhnuIswYXWLLuns',
    appId: '1:707566372207:ios:f37363e650bc309a9d549a',
    messagingSenderId: '707566372207',
    projectId: 'texnik-ijodkorlik-ilhom-45503',
    storageBucket: 'texnik-ijodkorlik-ilhom-45503.firebasestorage.app',
    iosBundleId: 'com.example.texnikIjodkorlik',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBIGuWSDiF_DF0I2w-OBhnuIswYXWLLuns',
    appId: '1:707566372207:ios:f37363e650bc309a9d549a',
    messagingSenderId: '707566372207',
    projectId: 'texnik-ijodkorlik-ilhom-45503',
    storageBucket: 'texnik-ijodkorlik-ilhom-45503.firebasestorage.app',
    iosBundleId: 'com.example.texnikIjodkorlik',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBj05IIio8fdDxMJcQAo3VTSb-PQMeG4Do',
    appId: '1:707566372207:web:ef55c05759ae1e3f9d549a',
    messagingSenderId: '707566372207',
    projectId: 'texnik-ijodkorlik-ilhom-45503',
    authDomain: 'texnik-ijodkorlik-ilhom-45503.firebaseapp.com',
    storageBucket: 'texnik-ijodkorlik-ilhom-45503.firebasestorage.app',
    measurementId: 'G-MCCDQF31F9',
  );
}
